# Generated by Django 2.1.2 on 2018-10-23 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('display_name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
