# Generated by Django 2.1.2 on 2018-10-23 21:15

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('display_name', models.TextField()),
                ('type', models.CharField(choices=[('temperature', 'Temperature (deg C)'), ('humidity', 'Humidity (%)'), ('speed', 'Speed (km/h)'), ('power', 'Power (W)'), ('distance', 'Distance (m)'), ('rotation', 'Rotation (deg)'), ('brightness', 'Brightness (%)'), ('image', 'Image (URL)'), ('state', 'State (on/off)'), ('direction', 'Direction'), ('other', 'Other')], max_length=16)),
                ('value', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('display_name', models.TextField()),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domains.Domain')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='property',
            name='thing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='things.Thing'),
        ),
    ]
